# Catppuccin Mocha (https://catppuccin.com/palette)
name = "catppuccin-mocha"
accent = "#89b4fa"
muted = "#585b70"
error = "#f38ba8"
warning = "#f9e2af"
success = "#a6e3a1"
code = "#89b4fa"
bg = "#1e1e2e"
text = "#cdd6f4"
