# Rosé Pine (https://rosepinetheme.com/palette)
name = "rose-pine"
accent = "#9ccfd8"
muted = "#6e6a86"
error = "#eb6f92"
warning = "#f6c177"
success = "#31748f"
code = "#9ccfd8"
bg = "#191724"
text = "#e0def4"
panel_bg = "#191724"
border = "#6e6a86"
user_bg = "#211f2e"
