# Solarized Dark (https://ethanschoonover.com/solarized/)
name = "solarized-dark"
accent = "#268bd2"
muted = "#586e75"
error = "#dc322f"
warning = "#b58900"
success = "#859900"
code = "#268bd2"
bg = "#002b36"
text = "#839496"
panel_bg = "#002b36"
border = "#586e75"
