# Tokyo Night (https://github.com/folke/tokyonight.nvim)
name = "tokyonight-night"
accent = "#7aa2f7"
muted = "#565f89"
error = "#f7768e"
warning = "#e0af68"
success = "#9ece6a"
code = "#7aa2f7"
bg = "#1a1b26"
text = "#c0caf5"
panel_bg = "#1a1b26"
border = "#565f89"
user_bg = "#22232f"
